
export const REQUEST_CHECKOUT = 'REQUEST_CHECKOUT';
export const SUCCESS_CHECKOUT = 'SUCCESS_CHECKOUT';
export const FAILURE_CHECKOUT = 'FAILURE_CHECKOUT';
export const DELETE_CHECKOUT_ERROR = 'DELETE_CHECKOUT_ERROR';
